# Generated by Django 5.0 on 2024-04-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streamingvariable",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Streaming Variable",
                "verbose_name_plural": "Streaming Variables",
            },
        ),
        migrations.AlterModelTable(
            name="streamingvariable",
            table="streaming_variable",
        ),
    ]
