# Generated by Django 5.0 on 2024-04-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exp_app", "0002_alter_streamingvariable_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streamingvariable",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Streaming Variable",
                "verbose_name_plural": "Streaming Variables",
            },
        ),
    ]
