# Generated by Django 5.0 on 2024-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exp_app", "0003_alter_streamingvariable_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateMetrics",
            fields=[
                (
                    "state",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("avg_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sd_value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["state"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="streamingvariable",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Streaming Variable",
                "verbose_name_plural": "Streaming Variables",
            },
        ),
    ]
